### ISSUE TITLE
Is there a way to use this framework for identifying image manipulation; without the treatment and control setting?

### ISSUE THREAD

**Issue by codepujan** [Cyrilvallez/Image-manipulation-detection#2]
Great work with the overall framework and setting up the benchmark. 
The control and treatment setting confused me a lot. 
Let's say I have a bunch of source images, and a pool of images that are manipulated versions of the images, with the corresponding ground truth for each source image.
For every source image, I want to benchmark the different algorithms on identifying the correct set of manipulated images. Is there a proper way to go about this? 
Thanks

**Comment by chiffa** [comment]
Yes - set the database, run the perturbation generator and then replace the generated folder with images from your manipulated dataset. At this point you can follow the steps outlined in the README to get the statistics and the figures. 

Hope that helps!

**Comment by codepujan** [comment]
Thank you for the quick response @Cyrilvallez . The setup works in the case of above snippet. I am interested  to identify true negatives, and false positives as well. In that case, I am still finding it difficult to understand the split of experimental / control groups ( I even read the paper) used in the benchmark. 
Revisiting the setup ; I have source images (s1,...s10). And a bunch of images that are manipulation of each source. And there are  a set of images that are _noise_ and not related to any of the  source images at all. How would I go about dividing the experimental and control groups in this setting?
Thank you for the help.

**Comment by Cyrilvallez** [comment]
Well then the experimental group would be the manipulations of the source images (images that are supposed to be detected), and the control would be the noisy images (images not supposed to be detected). However, if both groups do not contain the exact same number of images, be aware that the statistics computed (accuracy, precision, etc...) are NOT normalized against the number of images in each group (as we always used the same number of images in each group). Thus it can be misleading in the case of (large) imbalance between both groups.

Using this setup, you can simply follow all steps of the README using the experimental and control groups defined above  as `positive_dataset` and `negative_dataset` respectively:

```python
positive_dataset = hashing.create_dataset('path/to/experimental', existing_attacks=True)
negative_dataset = hashing.create_dataset('path/to/control', existing_attacks=True)
```
